name: Snake Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your build steps here

      - name: Generate Snake Workflow SVG
        uses: pvig/snake-workflows@v1
        with:
          actionsToken: ${{ secrets.GITHUB_TOKEN }}
          runWorkflow: ${{ github.workflow }}
          outputFile: snake-workflow.svg

      - name: Copy SVG to Root Directory
        run: mv snake-workflow.svg $GITHUB_WORKSPACE/snake-workflow.svg
